name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # hourly updates
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
